Task 2
oDoLaReKo/react-example-app pull request #5
Opened 2022-05-10 22:59 UTC by oDoLaReKo

I think that it shoud be ok now. I was very confused with those commit's

2022-05-13 18:38 UTC, oDoLaReKo commented
3 errors:
1. There is problem with id that is assigned but never used idk why becouse it is used in 70 line " <Square key={id} color={square.color} /> : square.shape === 'circle'"
2. square is already declared in upper scope i read about it and this is a bug that we can changed by adding 
"no-shadow": "off",
"@typescript-eslint/no-shadow": ["error"] 
but I'll wait for your opinion
3. do not nest ternary expression i do not understand why

2022-05-17 21:59 UTC, kaz231 requested changes

2022-05-17 21:59 UTC, kaz231 commented on src/components/SquareBox/SquareBox.tsx
> +};
Format this code pls

2022-05-17 21:59 UTC, kaz231 commented on src/components/SquareBox/SquareBox.tsx
> +            ? <Circle key={id} color={square.color} /> : 0))}
```suggestion
        {squares.map((square: Shape) => square.shape === 'square'
          ? <Square key={id} color={square.color} /> : <Circle key={id} color={square.color} />)}
```

We have to options so we can check only one shape and use the other as default.

Use should use `id` from line 37, not the index from map function.

2022-05-17 21:59 UTC, kaz231 commented on src/components/SquareBox/SquareBox.tsx
> +  }
Move this interface outside of SquareBox function, the body of SquareBox is re-run every time when the view has to be refreshed, so this interface is reacted over and over again.

2022-05-17 21:59 UTC, kaz231 commented on src/components/SquareBox/SquareBox.tsx
> +    setSquares((squares) => ([
squares is already declared in 38, you should rather alias it

```
setSquares((prevSquares) => ...)
```

2022-05-18 12:13 UTC, oDoLaReKo commented on src/components/SquareBox/SquareBox.tsx
> -    setSquares((squares) => [...squares]);
in this and in line 38 squares are not required but what to do with line 50 how should i change it ?

2022-05-19 12:11 UTC, merged